name: Development Build (Galaxy A50)

on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'wip-*'

jobs:
  oneui-s-e:
    name: Build One UI 5 (Enforcing)
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      
    steps:
    - name: Set up Android environment
      uses: android-actions/setup-android@v2
      with:
        sdk-version: '13'
        build-tools-version: '32.0.0'
        target-platform: 'android-33'

    - name: Update Debian/Ubuntu Repositories
      run: sudo apt-get update

    - name: Install Debian/Ubuntu dependencies
      run: sudo apt-get install bzip2 lib32stdc++6 libc6-dev-i386 libncurses5 jq -y

    - name: Build Mint kernel
      run: |
          set -eo pipefail
          echo "  I: Building Mint kernel ${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER}"
          ./build.sh --magisk --automated --device a50 --variant oneui --android 13

    # Steps for preparing release package, uploading artifacts, and cleaning up remain unchanged

  oneui-s-m:
    name: Build One UI 5 (Enforcing; Magisk Canary)
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      
    steps:
    - name: Set up Android environment
      uses: android-actions/setup-android@v2
      with:
        sdk-version: '13'
        build-tools-version: '32.0.0'
        target-platform: 'android-33'

    # Remaining steps similar to oneui-s-e job

  oneui-s-p:
    name: Build One UI 5 (Permissive)
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      
    steps:
    - name: Set up Android environment
      uses: android-actions/setup-android@v2
      with:
        sdk-version: '13'
        build-tools-version: '32.0.0'
        target-platform: 'android-33'

    # Remaining steps similar to oneui-s-e job

  # Jobs for other variants (Magisk Canary, AOSP, etc.) follow a similar structure with Android 13 setup.

  release:
    name: Release files and configs
    if: ${{ !contains(github.event.head_commit.message, '[skip rel]') }}
    needs: [oneui-s-e, oneui-s-p, oneui-r-e, oneui-r-p, aosp-s-e, aosp-s-p, aosp-r-e, aosp-r-p]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v2

    # Remaining steps for merging releases, deleting old releases, and uploading new releases remain unchanged
